# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: /run/secrets/db_password

    secrets:
      - db_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


  # nodered:
  #   image: nodered_horno_komatsu
  #   restart: always
  #   ports:
  #     - 1880:1880
    

  #   network_mode: "host"


  secrets:
    db_password:
      file: ./secrets/db_password.txt