# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


  nodered:
    image: dpflores/nodered_komatsu:saving
    restart: always
    ports:
      - 1880:1880
      
secrets:
  db_root_password:
    file: ./secrets/db_password.txt

